- hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
    become_user_name: null
    become_user_password: null

  tasks:
    - name: security
      ibmi_sql_query:
        sql: SELECT * from qsys2.security_info;
                  
        become_user: '{{ become_user_name }}'
        become_user_password: '{{ become_user_password }}'
      register: security
      tags: security
      ignore_errors: true
    - debug:
       msg : "la securit√© est {{ security.stdout }}"